import { MenuItem, Table, LanguageStrings } from '../types';

export const TRANSLATIONS: Record<'en' | 'sw', LanguageStrings> = {
  en: {
    welcome: "Welcome to Manna Restaurant",
    tagline: "Arusha's Premier Digital Dining Experience",
    roleSelect: "Switch Role view to see integration in real-time:",
    customerRole: "📱 Customer Portal",
    waiterRole: "💼 Waiter View",
    kitchenRole: "🍳 Kitchen Display (KDS)",
    managerRole: "📊 Manager Web Dashboard",
    architectureBlueprint: "📐 System Architecture Blueprint",
    switchRoleMsg: "Act as a user by selecting a role from the control panel. All operations share a simulated real-time backend state.",
    backToTop: "Back to Top",
    swahili: "Kiswahili",
    english: "English",
    tzs: "TZS",

    // Customer
    customerPortalTitle: "Customer Portal (Mobile Native Optimized)",
    qrOrdering: "Table QR Ordering Enabled",
    tableNumber: "Table",
    selectYourTable: "Select Your Table No.",
    enterName: "Enter Your Name:",
    searchFoodPlaceholder: "Search delicious foods (e.g. Pilau, Nyama)...",
    allCategories: "All Categories",
    addToCart: "Add to Cart",
    addedToCart: "Added!",
    cart: "Cart Items",
    cartEmpty: "Your cart is empty. Tap any dish to add it!",
    specialInstructions: "Special Cooking Instructions",
    specialInstructionsDesc: "e.g., 'pilipili kali sana' or 'no salt on chips'",
    paymentMethod: "Payment Method",
    placeOrder: "Place Order (Swasiland/Tanzania Direct)",
    orderPlacing: "Transmitting to Kitchen...",
    activeOrderHeading: "Your Order is Submitted!",
    trackOrderStatus: "Real-time Order Status Tracer",
    orderReceived: "Order Received by Waiter & Kitchen",
    orderCooking: "Cooking in Progress",
    orderReady: "Order Ready - Hot & Delicious!",
    orderServed: "Served on Table",
    orderPaid: "Completed & Paid. Asante sana for dining with Manna!",
    paymentMethodPlaceholder: "Select Payment Gateway",
    cashOnPayment: "Pay with Cash at Counter",
    tanzaniaMobilePay: "Mobile Money Terminal (LUKU PIN automatic)",
    paySuccessMessage: "Waiting for Sim Application Toolkit (M-Pesa/Airtel/Tigo) Payment Prompt...",

    // Waiter
    waiterPortalTitle: "Waiter Operations Console (Tablet Layout)",
    tablesGrid: "Restaurant Tables Grid & Alert Center",
    activeOrders: "Assigned Table Statuses",
    newManualOrder: "Add Manual Order for Walk-in",
    assignTable: "Assign Waiter",
    createOrder: "Send Order",
    sentToKitchen: "Transmitted to Kitchen Display System",
    markAsServed: "Mark Food Served to Client",
    receivedFoodAlert: "KITCHEN ALERTS: Food is hot & ready to serve!",

    // Kitchen
    kitchenPortalTitle: "Kitchen Display System (KDS) Queue",
    activeTickets: "Active Kitchen Tickets (Auto Sorted by Wait-time)",
    noOrders: "Kuku safi! No orders pending in the queue right now.",
    itemNotes: "Siri ya upishi (Notes):",
    bumpCooking: "Start Cooking",
    bumpReady: "Mark Ready for Pick",
    completedOrders: "Bumped/Completed Orders",
    priorityHigh: "HIGH PRIORITY",
    priorityNormal: "NORMAL PRIORITY",

    // Manager
    managerPortalTitle: "Manna Executive Management Hub",
    totalSales: "Total Daily Sales Volume",
    pendingOrders: "Pending Active Tickets",
    avgPreparationTime: "Avg Cooking Turnaround",
    menuManagement: "Local Menu Creator & Editor",
    addMenuItem: "Add New Dish",
    editItem: "Modify Properties",
    saveItem: "Apply Changes",
    deleteItem: "Retire Dish",
    reportsAnalytics: "Operational Sales Dashboard",
    swahiliName: "Name in Swahili",
    englishName: "Name in English",
    category: "Menu Grouping",
    price: "Price in Tanzanian Shilling (TZS)",
  },
  sw: {
    welcome: "Karibu Manna Restaurant",
    tagline: "Huduma Bora ya Chakula ya Kidijitali Arusha",
    roleSelect: "Badili jukumu kuona ujumuishaji kwa wakati halisi:",
    customerRole: "📱 Jukwaa la Mteja",
    waiterRole: "💼 Jukwaa la Muhudumu",
    kitchenRole: "🍳 Skrini ya Jikoni (KDS)",
    managerRole: "📊 Dashibodi ya Meneja",
    architectureBlueprint: "📐 Ramani na Usanifu wa Mfumo",
    switchRoleMsg: "Ili kuona jinsi mfumo unavyofanya kazi, badilisha jukumu juu. Mifumo yote inashiriki hifadhidata moja kwa wakati halisi.",
    backToTop: "Rudi Juu",
    swahili: "Kiswahili",
    english: "Kingereza",
    tzs: "TSH",

    // Customer
    customerPortalTitle: "Jukwaa la Mteja (Simu ya Mkononi)",
    qrOrdering: "Kuagiza kupitia QR Code Kwenye Meza",
    tableNumber: "Meza",
    selectYourTable: "Chagua Namba ya Meza Yako",
    enterName: "Weka Jina Lako:",
    searchFoodPlaceholder: "Tafuta vyakula vitamu (mf. Chips, Nyama)...",
    allCategories: "Makundi Yote",
    addToCart: "Weka Kwenye Kikapu",
    addedToCart: "Imewekwa!",
    cart: "Kikapu Chako",
    cartEmpty: "Kikapu chako kiko wazi. Gonga chakula kuongeza!",
    specialInstructions: "Maelekezo Maalum ya Mapishi",
    specialInstructionsDesc: "mf., 'pilipili kali sana' au 'chips isiwekwe chumvi'",
    paymentMethod: "Njia ya Malipo",
    placeOrder: "Wasilisha Oda (Mpigie Mpishi Jikoni)",
    orderPlacing: "Inatuma oda jikoni...",
    activeOrderHeading: "Oda Yako Imepokelewa!",
    trackOrderStatus: "Ufuatiliaji wa Oda Yako kwa Wakati Halisi",
    orderReceived: "Oda Imepokelewa na Jiko",
    orderCooking: "Chakula Kinaandaliwa Jikoni",
    orderReady: "Chakula Kiko Tayari - Cha Moto & Kitamu!",
    orderServed: "Kimeshawasilishwa Mezani Kwako",
    orderPaid: "Malipo Yamekamilika. Asante sana kwa kuchagua Manna!",
    paymentMethodPlaceholder: "Chagua Njia ya Malipo",
    cashOnPayment: "Lipa kwa Fedha Taslimu Kasiri",
    tanzaniaMobilePay: "Malipo ya Simu (M-Pesa / Tigo Pesa / Airtel)",
    paySuccessMessage: "Inasubiri uthibitisho wa muamala wa Simu yako...",

    // Waiter
    waiterPortalTitle: "Dashibodi ya Muhudumu (Kompyuta Kibao)",
    tablesGrid: "Hali ya Meza na Arifa Restorani nyepesi",
    activeOrders: "Hali ya Meza Zilizopangiwa",
    newManualOrder: "Andika Oda Mpya kwa Mteja",
    assignTable: "Mhudumu Aliyechaguliwa",
    createOrder: "Wasilisha Oda",
    sentToKitchen: "Imetumwa Jikoni Kwenye Mifumo",
    markAsServed: "Weka 'Kimeshaandaliwa Mezani'",
    receivedFoodAlert: "ARIFA YA JIKONI: Chakula kiko tayari kupelekwa kwa mteja!",

    // Kitchen
    kitchenPortalTitle: "Mfumo wa KDS wa Jikoni",
    activeTickets: "Tiketi za Vyakula Vinavyosubiri Upishi",
    noOrders: "Safi sana! Hakuna oda inayongoja jikoni sasa hivi.",
    itemNotes: "Maagizo (Notes):",
    bumpCooking: "Anza Kupika",
    bumpReady: "Weka 'Tayari'",
    completedOrders: "Oda Zilizokamilika",
    priorityHigh: "KIPAUMBELE CHA JUU",
    priorityNormal: "KIPAUMBELE CHA KAWAIDA",

    // Manager
    managerPortalTitle: "Meneja mkuu - Manna System Terminal",
    totalSales: "Mauzo ya Leo kwa TSH",
    pendingOrders: "Oda Zinazoendelea Sasa",
    avgPreparationTime: "Muda Wastani wa Mapishi",
    menuManagement: "Meneja wa Vyakula na Bei jikoni",
    addMenuItem: "Weka Chakula Kipya",
    editItem: "Badili Tabia",
    saveItem: "Hifadhi Mabadiliko",
    deleteItem: "Ondoa Chakula",
    reportsAnalytics: "Taarifa ya Mapato na Utendaji",
    swahiliName: "Jina kwa Kiswahili",
    englishName: "Jina kwa Kingereza",
    category: "Kundi la Chakula",
    price: "Bei kwa Shilingi za Kitanzania (TSH)",
  }
};

export const INITIAL_MENU: MenuItem[] = [
  {
    id: "m1",
    nameEn: "Chips Mayai Special",
    nameSw: "Chips Mayai Maarufu",
    descEn: "Classic French fries omelette, served with kachumbari salad and homemade chili.",
    descSw: "Chips safi zilizokaangwa na mayai mawili, pamoja na kachumbari na pilipili ya nyumbani.",
    price: 4500,
    category: "specials",
    image: "chips_mayai",
    isAvailable: true
  },
  {
    id: "m2",
    nameEn: "Nyama Choma Platters",
    nameSw: "Plata ya Nyama Choma tetema",
    descEn: "Premium tender beef local cut, grilled slowly on charcoal, served with kachumbari and ugali.",
    descSw: "Nyama ya ng'ombe laini choma ya mkaa upishi polepole, na kachumbari na ugali.",
    price: 12000,
    category: "food",
    image: "nyama_choma",
    isAvailable: true
  },
  {
    id: "m3",
    nameEn: "Pilau Kuku ya Arusha",
    nameSw: "Pilau la Kuku la Arusha",
    descEn: "Fragrant Tanzanian spiced rice cooked cooked with ginger, garlic, and locally sourced chicken.",
    descSw: "Pilau yenye viungo vizuri vya Arusha iliyopikwa kwa tangawizi, vitunguu saumu na kuku wa kienyeji.",
    price: 8500,
    category: "specials",
    image: "pilau_rice",
    isAvailable: true
  },
  {
    id: "m4",
    nameEn: "Ugali na Naazi Samaki",
    nameSw: "Ugali na Samaki wa Nazi",
    descEn: "Tanzanian white maize meal served with deep fried tilapia topped with rich sweet coconut curry sauce.",
    descSw: "Ugali safi wa mahindi meupe uliosindikizwa na tilapia kukaangwa na mchuzi mtamu wa nazi.",
    price: 11000,
    category: "food",
    image: "ugali_samaki",
    isAvailable: true
  },
  {
    id: "m5",
    nameEn: "Samosa za Nyama (2pcs)",
    nameSw: "Sambusa za Nyama (Mbili)",
    descEn: "Crispy beef pastries seasoned with Tanzanian cardamom and sweet onions.",
    descSw: "Sambusa mbili za nyama zenye viungo safi na vitunguu, zimekaangwa zikawa na ubaridi mtamu.",
    price: 2000,
    category: "sides",
    image: "samosas",
    isAvailable: true
  },
  {
    id: "m6",
    nameEn: "Mchapati Mtamu wa Siagi",
    nameSw: "Chapati ya Mafuta na Siagi",
    descEn: "Soft layered East African pan-fried flatbread, perfect with tea or direct meals.",
    descSw: "Chapati laini ya tabaka za siagi kwa mlo au kunywea chai asubuhi au jioni.",
    price: 1500,
    category: "sides",
    image: "chapati",
    isAvailable: true
  },
  {
    id: "m7",
    nameEn: "Safari Lager",
    nameSw: "Bia ya Safari",
    descEn: "Famous crisp Tanzanian lager representing regional taste of active adventure.",
    descSw: "Bia maarufu yenye ladha nzuri na baridi, kiburudisho tosha cha Kitalii.",
    price: 4000,
    category: "drink",
    image: "safari_lager",
    isAvailable: true
  },
  {
    id: "m8",
    nameEn: "Milk Tea with Cardamom",
    nameSw: "Chai ya Maziwa ya Iliki",
    descEn: "Aromatic black tea leaves brewed with fresh cow milk and organic iliki.",
    descSw: "Chai tamu ya maziwa iliyochemshwa na majani ya chai ya kienyeji na iliki safi ya Arusha.",
    price: 1500,
    category: "drink",
    image: "tea",
    isAvailable: true
  },
  {
    id: "m9",
    nameEn: "Kilimanjaro Pure Water 1L",
    nameSw: "Maji ya Kilimanjaro 1L",
    descEn: "Clean natural mineral water bottled directly at Mount Kilimanjaro.",
    descSw: "Maji safi ya asili na baridi yaliyochujwa tangu mlima Kilimanjaro.",
    price: 1500,
    category: "drink",
    image: "water_kili",
    isAvailable: true
  }
];

export const INITIAL_TABLES: Table[] = [
  { id: 1, number: "T1 (Kona)", status: "empty" },
  { id: 2, number: "T2 (Mlangoni)", status: "empty" },
  { id: 3, number: "T3 (VIP Up)", status: "empty" },
  { id: 4, number: "T4 (Kikao)", status: "empty" },
  { id: 5, number: "T5 (Bustani)", status: "empty" },
  { id: 6, number: "T6 (Bar Counter)", status: "empty" }
];
